---
- hosts: ios
  gather_facts: no
  tasks:
  - name: Cisco cfg backup
    ios_config:
     backup: yes
     backup_options:
     filename: "{{ inventory_hostname }}"
     dir_path: ./
-name: read config to gitlab
 set_fact:
  file content: "{{ item }}"
 with_file:
-name: push cfg to gitlab
uri: https://gitlab.com//projects/{{ gitlab_project_id }}/repository/tree?ref=master&per_page=100&page=1
headers:
  Privite_token: "{{ gitlab_access_token }}"
  validate certs: no
method: POST
body: master
commit_message: create cisco backup cfg
actions:
  - actions: create
    file_path: "{{ inventory_hostname }}"
    content: "{{ file_content }}"
status_code: 201
body_format: json




{
  "branch": "master"
  "commit_message": "some commit message"
  "actions":[
    {
      "action": "create",
      "file_path": "foo/bar",
      "content": "some content"
    }
  ]
     }